# Pandas Playground and intro
personal practice with Lahman data that i used Rstudio to write the Lahman databases to CSVs

#### **Tables / CSV Files I Have Currently Working:**
People, Appearances, Batting, Pitching, Teams

In [13]:
import pandas as pd
people = pd.read_csv('data/People.csv')

people

,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,deathDay,...,weight,height,bats,throws,debut,bbrefID,finalGame,retroID,deathDate,birthDate
0,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,NaN,...,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001,NaN,1981-12-27
1,aaronha01,1934.0,2.0,5.0,Mobile,USA,AL,2021.0,1.0,22.0,...,180.0,72.0,R,R,1954-04-13,aaronha01,1976-10-03,aaroh101,2021-01-22,1934-02-05
2,aaronto01,1939.0,8.0,5.0,Mobile,USA,AL,1984.0,8.0,16.0,...,190.0,75.0,R,R,1962-04-10,aaronto01,1971-09-26,aarot101,1984-08-16,1939-08-05
3,aasedo01,1954.0,9.0,8.0,Orange,USA,CA,NaN,NaN,NaN,...,190.0,75.0,R,R,1977-07-26,aasedo01,1990-10-03,aased001,NaN,1954-09-08
4,abadan01,1972.0,8.0,25.0,Palm Beach,USA,FL,NaN,NaN,NaN,...,184.0,73.0,L,L,2001-09-10,abadan01,2006-04-13,abada001,NaN,1972-08-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21005,paysojo99,1903.0,2.0,5.0,New York,USA,NY,1975.0,10.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1975-10-04,1903-02-05
21006,galbrjo99,1897.0,8.0,10.0,Derby,USA,OH,1988.0,7.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1988-07-20,1897-08-10
21007,mcshejo99,1944.0,9.0,11.0,Bronx,USA,NY,1996.0,4.0,1.0,...,351.0,75.0,NaN,NaN,NaN,NaN,NaN,mcshj901,1996-04-01,1944-09-11
21008,weyerle99,1936.0,9.0,3.0,Imlay City,USA,MI,1988.0,7.0,4.0,...,258.0,78.0,NaN,NaN,NaN,NaN,NaN,weyel901,1988-07-04,1936-09-03
21009,palerst99,1949.0,10.0,9.0,Worcester,USA,MA,2017.0,5.0,14.0,...,175.0,74.0,NaN,NaN,NaN,NaN,NaN,pales901,2017-05-14,1949-10-09

In [14]:
birthyearpeople = people[people['birthYear'] == 1981]

birthyearpeople

,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,deathDay,...,weight,height,bats,throws,debut,bbrefID,finalGame,retroID,deathDate,birthDate
0,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,NaN,...,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001,NaN,1981-12-27
44,accarje01,1981.0,12.0,18.0,Phoenix,USA,AZ,NaN,NaN,NaN,...,195.0,72.0,R,R,2005-05-04,accarje01,2012-09-27,accaj001,NaN,1981-12-18
57,acostma01,1981.0,5.0,1.0,Colon,Panama,Colon,NaN,NaN,NaN,...,215.0,76.0,R,R,2007-08-12,acostma01,2012-10-03,acosm001,NaN,1981-05-01
367,anderdr01,1981.0,6.0,9.0,Kearney,USA,NE,NaN,NaN,NaN,...,195.0,74.0,L,R,2006-09-11,anderdr01,2006-10-01,anded002,NaN,1981-06-09
623,avilemi01,1981.0,3.0,13.0,New York,USA,NY,NaN,NaN,NaN,...,205.0,70.0,R,R,2008-05-29,avilemi01,2017-10-01,avilm001,NaN,1981-03-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20070,willire03,1981.0,5.0,30.0,Chickasha,USA,OK,NaN,NaN,NaN,...,185.0,71.0,B,R,2006-04-26,willire03,2011-06-03,willr004,NaN,1981-05-30
20147,wilsojo03,1981.0,3.0,26.0,Pittsburgh,USA,PA,NaN,NaN,NaN,...,175.0,72.0,R,R,2005-09-07,wilsojo03,2015-10-04,wilsj003,NaN,1981-03-26
20341,woodsja01,1981.0,9.0,3.0,Fresno,USA,CA,NaN,NaN,NaN,...,190.0,73.0,L,L,2005-04-08,woodsja01,2008-09-18,woodj002,NaN,1981-09-03
20592,zambrca01,1981.0,6.0,1.0,Puerto Cabello,Venezuela,Carabobo,NaN,NaN,NaN,...,275.0,76.0,B,R,2001-08-20,zambrca01,2012-09-21,zambc001,NaN,1981-06-01
20660,zobribe01,1981.0,5.0,26.0,Eureka,USA,IL,NaN,NaN,NaN,...,210.0,75.0,B,R,2006-08-01,zobribe01,2019-09-29,zobrb001,NaN,1981-05-26

In [15]:
birthyearandstatepeople = people[(people['birthYear'] == 1981) & (people['birthState'] == 'AL')]

birthyearandstatepeople

,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,deathDay,...,weight,height,bats,throws,debut,bbrefID,finalGame,retroID,deathDate,birthDate
14351,peavyja01,1981.0,5.0,31.0,Mobile,USA,AL,NaN,NaN,NaN,...,195.0,73.0,R,R,2002-06-22,peavyja01,2016-09-21,peavj001,NaN,1981-05-31
15642,riosal01,1981.0,2.0,18.0,Coffee,USA,AL,NaN,NaN,NaN,...,210.0,77.0,R,R,2004-05-27,riosal01,2015-10-04,riosa002,NaN,1981-02-18
15725,roberco01,1981.0,9.0,10.0,Tuscaloosa,USA,AL,NaN,NaN,NaN,...,225.0,74.0,R,R,2007-05-17,roberco01,2008-07-18,robec002,NaN,1981-09-10

In [16]:
birthyearandstatepeople['playerID'].unique

<bound method Series.unique of 14351    peavyja01
15642     riosal01
15725    roberco01
Name: playerID, dtype: object>

In [17]:
birthyearandstatepeople.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 14351 to 15725
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   playerID      3 non-null      object
 1   birthYear     3 non-null      float64
 2   birthMonth    3 non-null      float64
 3   birthDay      3 non-null      float64
 4   birthCity     3 non-null      object
 5   birthCountry  3 non-null      object
 6   birthState    3 non-null      object
 7   deathYear     0 non-null      float64
 8   deathMonth    0 non-null      float64
 9   deathDay      0 non-null      float64
 10  deathCountry  0 non-null      object
 11  deathState    0 non-null      object
 12  deathCity     0 non-null      object
 13  nameFirst     3 non-null      object
 14  nameLast      3 non-null      object
 15  nameGiven     3 non-null      object
 16  weight        3 non-null      float64
 17  height        3 non-null      float64
 18  bats          3 non-null      object
 19  throws        3 non-null      object
 20  debut         3 non-null      object
 21  bbrefID       3 non-null      object
 22  finalGame     3 non-null      object
 23  retroID       3 non-null      object
 24  deathDate     0 non-null      object
 25  birthDate     3 non-null      object
dtypes: float64(8), object(18)
memory usage: 648.0+ bytes

Sort by height ascending and weight descending

In [ ]:
birthyearandstatepeople.sort_values(
    by =['weight', 'height'],  # Columns to sort by
    ascending=[False, True]     # weight DESC, height ASC
)

,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,deathDay,...,weight,height,bats,throws,debut,bbrefID,finalGame,retroID,deathDate,birthDate
15725,roberco01,1981.0,9.0,10.0,Tuscaloosa,USA,AL,NaN,NaN,NaN,...,225.0,74.0,R,R,2007-05-17,roberco01,2008-07-18,robec002,NaN,1981-09-10
15642,riosal01,1981.0,2.0,18.0,Coffee,USA,AL,NaN,NaN,NaN,...,210.0,77.0,R,R,2004-05-27,riosal01,2015-10-04,riosa002,NaN,1981-02-18
14351,peavyja01,1981.0,5.0,31.0,Mobile,USA,AL,NaN,NaN,NaN,...,195.0,73.0,R,R,2002-06-22,peavyja01,2016-09-21,peavj001,NaN,1981-05-31

In [19]:
birthyearandstatepeople[
    birthyearandstatepeople['throws'] == 'R'
].sort_values(
    by=['weight', 'height'],  # Columns to sort by
    ascending=[False, False]     # weight DESC, height ASC
)

,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,deathDay,...,weight,height,bats,throws,debut,bbrefID,finalGame,retroID,deathDate,birthDate
15725,roberco01,1981.0,9.0,10.0,Tuscaloosa,USA,AL,NaN,NaN,NaN,...,225.0,74.0,R,R,2007-05-17,roberco01,2008-07-18,robec002,NaN,1981-09-10
15642,riosal01,1981.0,2.0,18.0,Coffee,USA,AL,NaN,NaN,NaN,...,210.0,77.0,R,R,2004-05-27,riosal01,2015-10-04,riosa002,NaN,1981-02-18
14351,peavyja01,1981.0,5.0,31.0,Mobile,USA,AL,NaN,NaN,NaN,...,195.0,73.0,R,R,2002-06-22,peavyja01,2016-09-21,peavj001,NaN,1981-05-31

In [20]:
testing_people = people[(people['birthYear'] >= 1970) & (people['height'] <= 66)]
testing_people

,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,deathDay,...,weight,height,bats,throws,debut,bbrefID,finalGame,retroID,deathDate,birthDate
304,altuvjo01,1990.0,5.0,6.0,Puerto Cabello,Venezuela,Carabobo,NaN,NaN,NaN,...,166.0,66.0,R,R,2011-07-20,altuvjo01,2022-10-04,altuj001,NaN,1990-05-06
335,amarial01,1989.0,4.0,6.0,Barcelona,Venezuela,Anzoategui,NaN,NaN,NaN,...,160.0,66.0,L,R,2011-04-26,amarial01,2017-10-01,amara001,NaN,1989-04-06
5231,eckstda01,1975.0,1.0,20.0,Sanford,USA,FL,NaN,NaN,NaN,...,170.0,66.0,R,R,2001-04-03,eckstda01,2010-10-03,ecksd001,NaN,1975-01-20
5987,fonvich01,1971.0,3.0,5.0,Jacksonville,USA,NC,NaN,NaN,NaN,...,155.0,66.0,B,R,1995-04-28,fonvich01,1999-07-09,fonvc001,NaN,1971-03-05
8195,herreda01,1984.0,10.0,21.0,Odessa,USA,TX,NaN,NaN,NaN,...,165.0,66.0,L,L,2008-06-03,herreda01,2011-09-27,herrd001,NaN,1984-10-21
9707,kempto01,1991.0,10.0,31.0,Franklin,USA,TN,NaN,NaN,NaN,...,160.0,66.0,L,R,2016-05-17,kempto01,2022-10-05,kempt001,NaN,1991-10-31
15110,quiroes01,1992.0,2.0,17.0,Ciudad Obregon,Mexico,Sonora,NaN,NaN,NaN,...,199.0,66.0,L,R,2022-09-17,quiroes01,2022-10-05,quire001,NaN,1992-02-17
16270,sadledo01,1975.0,6.0,17.0,Clifton,USA,TX,NaN,NaN,NaN,...,165.0,66.0,R,R,1998-04-01,sadledo01,2007-05-12,sadld001,NaN,1975-06-17
20731,fletcdo01,1997.0,9.0,2.0,Orange,USA,CA,NaN,NaN,NaN,...,185.0,66.0,L,L,2023-04-30,fletcdo01,2023-07-06,fletd003,NaN,1997-09-02
20820,andrecl02,1997.0,1.0,4.0,Petaluma,USA,CA,NaN,NaN,NaN,...,160.0,66.0,L,L,2023-07-01,andrecl02,2023-09-29,andrc002,NaN,1997-01-04

In [21]:
people.query('birthYear > 1970 and height < 70')

,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,deathDay,...,weight,height,bats,throws,debut,bbrefID,finalGame,retroID,deathDate,birthDate
138,aguilmi01,1991.0,9.0,26.0,Ciudad Obregon,Mexico,Sonora,NaN,NaN,NaN,...,194.0,68.0,L,L,2021-07-30,aguilmi01,2021-09-12,aguim001,NaN,1991-09-26
169,albieoz01,1997.0,1.0,7.0,Willemstad,Curacao,NaN,NaN,NaN,NaN,...,165.0,68.0,B,R,2017-08-01,albieoz01,2022-09-17,albio001,NaN,1997-01-07
181,alcanse01,1996.0,7.0,10.0,Santo Domingo Este,D.R.,Santo Domingo,NaN,NaN,NaN,...,151.0,69.0,B,R,2020-09-06,alcanse01,2022-10-05,alcas002,NaN,1996-07-10
249,allenni02,1998.0,10.0,8.0,San Diego,USA,CA,NaN,NaN,NaN,...,166.0,68.0,R,R,2022-04-19,allenni02,2022-10-05,allen002,NaN,1998-10-08
304,altuvjo01,1990.0,5.0,6.0,Puerto Cabello,Venezuela,Carabobo,NaN,NaN,NaN,...,166.0,66.0,R,R,2011-07-20,altuvjo01,2022-10-04,altuj001,NaN,1990-05-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20890,rafaece01,2000.0,9.0,18.0,Willemstad,Curacao,NaN,NaN,NaN,NaN,...,165.0,69.0,R,R,2023-08-28,rafaece01,2023-10-01,rafac001,NaN,2000-09-18
20894,dominja01,2003.0,2.0,7.0,Esperanza,D.R.,Valverde,NaN,NaN,NaN,...,190.0,69.0,B,R,2023-09-01,dominja01,2023-09-09,domij003,NaN,2003-02-07
20921,croplty01,1995.0,12.0,10.0,Sioux City,USA,IA,NaN,NaN,NaN,...,185.0,68.0,R,R,2023-09-19,croplty01,2023-09-23,cropt001,NaN,1995-12-10
20928,lopezir01,1995.0,6.0,30.0,Hermosillo,Mexico,Sonora,NaN,NaN,NaN,...,175.0,67.0,L,R,2023-09-23,lopezir01,2023-10-01,lopei001,NaN,1995-06-30
20976,correka99,1989.0,7.0,14.0,Hilo,USA,HI,NaN,NaN,NaN,...,165.0,69.0,R,R,NaN,correka99,NaN,corrk801,NaN,1989-07-14

In [23]:
Batting = pd.read_csv('data/Batting.csv')

HR_leaders = (
    Batting[['playerID', 'HR']]                    # select(playerID, HR)
    .groupby('playerID')                           # group_by(playerID)
    .agg(seasons_played=('HR', 'count'),           # summarise(seasons_played = n()
         total_HR=('HR', 'sum'),                   # sum(HR)
         mean_HR=('HR', 'mean'),                   # mean(HR)
         max_HR=('HR', 'max'))                     # max(HR)
    .reset_index()                                 # ungroup()
    .query('seasons_played > 20')                  # filter(seasons_played > 20)
)

In [24]:
HR_leaders

        playerID  seasons_played  total_HR    mean_HR  max_HR
1      aaronha01              23       755  32.826087      47
197    alexado01              23         0   0.000000       0
205    alexape01              21        11   0.523810       2
287    alomasa02              22       112   5.090909      21
307    altroni01              21         2   0.095238       1
...          ...             ...       ...        ...     ...
20493   wynnea01              23        17   0.739130       3
20522  yastrca01              23       452  19.652174      44
20582  youngcy01              23        18   0.782609       3
20634  zachato01              24         6   0.250000       2
20671  zeileto01              21       253  12.047619      31

[205 rows x 5 columns]