# Working with Pybaseball

### Gabe Rice
### Stats 336
### 3/25/25

It seems the closest thing to Lahman is the Python library pybaseball. Here's a link to the github page contaning more information then i'm going to type here: https://github.com/jldbc/pybaseball/tree/master. Going to start by replicating some things then moving onto creating queries more similar to the ones we've done in class.

Type into consle

In [ ]:
pip install pybaseball

Working through some online information

In [2]:
from pybaseball import statcast
data = statcast(start_dt='2017-06-24', end_dt='2017-06-27')
data.head(2)

This is a large query, it may take a moment to complete

  0%|                                                     | 0/4 [00:00<?, ?it/s]/Users/gabrielrice/miniforge3/lib/python3.12/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 25%|███████████▎                                 | 1/4 [00:00<00:01,  2.24it/s]/Users/gabrielrice/miniforge3/lib/python3.12/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Users/gabrielrice/miniforge3/lib/python3.12/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|██████████████████████▌                      | 2/4 [00:01<00:01,  1.92it/s]/Users/gabrielrice/miniforge3/lib/python3.12/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|█████████████████████████████████████████████| 4/4 [00:01<00:00,  3.00it/s]

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle
3384,CU,2017-06-27,79.7,-1.34,5.41,"Bush, Matt",608070,456713,field_out,hit_into_play,...,1,3,2,1,3,1,4.2,-0.82,0.82,<NA>
3448,FF,2017-06-27,98.1,-1.35,5.42,"Bush, Matt",429665,456713,field_out,hit_into_play,...,1,3,2,1,3,1,0.64,0.72,0.72,<NA>

In [3]:
from pybaseball import playerid_lookup
from pybaseball import statcast_pitcher
playerid_lookup('kershaw', 'clayton')

Gathering player lookup table. This may take a moment.

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,kershaw,clayton,477132,kersc001,kershcl01,2036,2008.0,2024.0

Seems to be working going to look into doing some batting queries

In [4]:
from pybaseball import batting_stats

# get all of this season's batting data so far
data = batting_stats(2017)

data.head(10)

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
1,15640,2017,Aaron Judge,NYY,25,155,542,678,154,75,...,121.1,186,0.550,338,0.157,0.290,0.287,0.668,0.450,8.8
6,5417,2017,Jose Altuve,HOU,27,153,590,662,204,137,...,109.1,143,0.280,511,0.161,0.233,0.291,0.477,0.360,7.5
11,13510,2017,Jose Ramirez,CLE,24,152,585,645,186,95,...,108.3,180,0.345,521,0.177,0.231,0.302,0.487,0.360,6.7
9,15429,2017,Kris Bryant,CHC,25,151,549,665,162,91,...,113.0,158,0.370,427,0.138,0.239,0.260,0.497,0.376,7.0
0,10155,2017,Mike Trout,LAA,25,114,402,507,123,62,...,114.7,128,0.405,316,0.193,0.255,0.294,0.589,0.425,6.4
4,4949,2017,Giancarlo Stanton,MIA,27,159,597,692,168,77,...,122.2,199,0.455,437,0.155,0.282,0.277,0.599,0.403,6.8
2,4314,2017,Joey Votto,CIN,33,162,559,707,179,108,...,110.9,158,0.328,482,0.149,0.207,0.299,0.555,0.416,6.1
37,9810,2017,Brian Dozier,MIN,30,152,617,705,167,99,...,111.8,165,0.345,478,0.191,0.283,0.244,0.468,0.342,6.1
13,12861,2017,Anthony Rendon,WSN,27,147,508,605,153,86,...,110.1,162,0.375,432,0.188,0.239,0.275,0.478,0.369,5.9
12,9777,2017,Nolan Arenado,COL,26,159,606,680,187,100,...,109.9,191,0.376,508,0.141,0.244,0.280,0.525,0.366,6.1